### PR TITLE
Sort Schema and Add CloudFormation Resources

### PR DESCRIPTION
**Pull request by arcaela**
## Overview

- Description:
  - I've arranged the JSON properties to be more readable.
  - Implemented the reference to AWS Labs CloudFormation for the serverless References property.
- Schema update type: extended
- Services affected: 

## How was this tested?
I have installed YAML for VSCode on my computer, then I have referenced the schema with the configuration: "yaml.schemas" and I have verified in the serverless.yaml and serverless.yml file that the "Resources" property is correctly loading the resources from AWS Labs CloudFormation.

### CODE REVIEW

**Comment by KillDozerX2** [comment]
I can't even open the diff on github, I'd need some time to view this, will hold merge till then

**Comment by KillDozerX2** [comment]
Can't go through 40K line changes, please wait for us to split the schema across multiple files before this can be looked at?
Could you try explaining what you did? I tried going through the diff but as I said, it's too many changes.
Watch #80 before we proceed.

**Comment by KillDozerX2** [comment]
@lalcebo I'd like to see what your view is on this.

**Comment by lalcebo** [comment]
@arcaela Do not apply style to the schema at the same time you introduce changes. It's hard to see what you added new, especially since you applied format the whole file.

**Comment by arcaela** [comment]
Yes, sorry.. I'll try again, but without styled schema.

**Pull request closed without merging**
