### PR TITLE
feat: split `reference.json` on sub schemas.

### PR DESCRIPTION
**Pull request by lalcebo**
## Overview

- Description: #79 
- Schema update type: modification
- Services affected: none

## References

- https://json-schema.org/understanding-json-schema/structuring.html

### CODE REVIEW

**Comment by lalcebo** [comment]
@KillDozerX2, look this. We need to move on this direction. The file has become too large and is difficult to maintain. Do some tests and check if everything is ok. If you have any idea of change, let me know.

**Comment by KillDozerX2** [comment]
Will do @lalcebo I definitely agree with this approach.

**Comment by KillDozerX2** [comment]
@lalcebo I just wanna add that it might be a good idea to create a build step which will build everything into a single schema. What do you think?

**Comment by lalcebo** [comment]
@KillDozerX2 It might be a good idea, an action that generates the final schema.

**Comment by KillDozerX2** [comment]
Cool, I'll come up with a build system soon

**Comment by KillDozerX2** [comment]
I don't think we need a build step, I just tested this in both vscode and intelliJ and it worked. I don't know of any other schema validators, but I say we merge this. It seems to be working as if it was one schema.

I say we merge it and start splitting and we'll handle a build step when someone comes asking for it.

**Comment by KillDozerX2** [comment]
Also, @lalcebo can we do Rebase and merge instead of merge commit? Gives out a cleaner git history which is easy to track.

**Comment by KillDozerX2** [comment]
Screenshot 2022-12-13 at 5 57 13 PM
I create a vscode snippet to quickly create sub schema

**Comment by lalcebo** [comment]
> I don't think we need a build step, I just tested this in both vscode and intelliJ and it worked. I don't know of any other schema validators, but I say we merge this. It seems to be working as if it was one schema.
> 
> I say we merge it and start splitting and we'll handle a build step when someone comes asking for it.

ok

**Comment by lalcebo** [comment]
> Also, @lalcebo can we do Rebase and merge instead of merge commit? Gives out a cleaner git history which is easy to track.

I agree. It is better.

**Review by KillDozerX2 — APPROVED** [review]

**Comment by KillDozerX2** [comment]
@lalcebo I think is good to go

**Pull request merged**
