### PR TITLE
chore: cleanup.

### PR DESCRIPTION
**Pull request by lalcebo**
@KillDozerX2 this is a cleanup PR. There is no need to keep the original CloudFormation schemas.

### CODE REVIEW

**Comment by KillDozerX2** [comment]
Let me review this please.

**Review by KillDozerX2 — CHANGES_REQUESTED** [review]
@lalcebo My philosophy behind this was to keep the original untouched and apply fixes to it that cloudformation doesn't provide, example:- enums for KeySchema in DynamoDB.

So if in the future, Cloudformation adds a new property or resource, we can directly adopt it without having to change our existing modified definitions.
This is the reason why both modified and original resource exist.
The new schemas also don't have default support for using Intrinsic functions and the script formats that.
Let's not do this.

**Comment by lalcebo** [comment]
@KillDozerX2  The original idea is maintained, the files are generated with `node index.js` I just changed the paths and remove the originals files. In the future we just download the zip from `https://schema.cloudformation.us-east-1.amazonaws.com/CloudformationSchema.zip` and, unzip it in the `cloudformation/` folder in the root of the project, I added this folder to `.gitignore`, like this that the original files will never be committed. When we generate the new files with `node index.js`, git will do its magic, and we will only see the new changes.

**Comment by KillDozerX2** [comment]
Yeah, but I've made some modifications, even to the original files. For example, I've added an enum for DynamoDB -> KeySchema -> KeyType, even the Cloudformation docs say that only two values are allowed, but for some reason the schema from Cloudformation specifies it as string. What do you think the solution would be here?

**Comment by lalcebo** [comment]
> Yeah, but I've made some modifications, even to the original files. For example, I've added an enum for DynamoDB -> KeySchema -> KeyType, even the Cloudformation docs say that only two values are allowed, but for some reason the schema from Cloudformation specifies it as string. What do you think the solution would be here?

I'm sorry, I didn't realize that, let me think about this. Of the original files, which ones have you modified?

**Comment by KillDozerX2** [comment]
I seriously can't remember. Focused on a lot of them. I will close this PR, I've made a few more updates till then.

**Pull request closed without merging**
